trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.12.1'
  TF_WORKING_DIR: '.'  # Your .tf file is in the root directory

steps:

# Step 1: Install Terraform v1.12.1
- script: |
    set -e
    echo "🔽 Downloading Terraform ${TF_VERSION}..."
    wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip

    echo "📦 Unzipping..."
    unzip terraform_${TF_VERSION}_linux_amd64.zip

    echo "🚚 Moving to /usr/local/bin"
    sudo mv terraform /usr/local/bin/

    echo "📌 Terraform version installed:"
    terraform version
  displayName: 'Install Terraform v1.12.1'

# Step 2: Checkout code
- checkout: self

# Step 3: Authenticate to Azure
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AZ-SPN-idmay25'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "✅ Azure login successful via service connection"
  displayName: 'Azure Login using SPN'

# Step 4: Terraform Init
- script: |
    terraform -chdir=$(TF_WORKING_DIR) init
  displayName: 'Terraform Init'

# ✅ Step 5: Terraform Format (Auto-Fix)
- script: |
    terraform -chdir=$(TF_WORKING_DIR) fmt
  displayName: 'Terraform Format (Auto-Fix)'

# Step 6: Terraform Validate
- script: |
    terraform -chdir=$(TF_WORKING_DIR) validate
  displayName: 'Terraform Validate'

# Step 7: Terraform Plan
- script: |
    terraform -chdir=$(TF_WORKING_DIR) plan -out=tfplan
  displayName: 'Terraform Plan'

# Optional Step 8: Apply the Plan
# - script: |
#     terraform -chdir=$(TF_WORKING_DIR) apply -auto-approve tfplan
#   displayName: 'Terraform Apply'
