trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.7.5'
  TF_WORKING_DIR: './terraform'  # change if your .tf files are in another directory

steps:

# Step 1: Install Terraform manually
- script: |
    sudo wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    sudo unzip terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin/
    terraform version
  displayName: 'Install Terraform'

# Step 2: Checkout your code
- checkout: self

# Step 3: Terraform Init
- script: |
    terraform -chdir=$(TF_WORKING_DIR) init
  displayName: 'Terraform Init'

# Step 4: Terraform Format Check
- script: |
    terraform -chdir=$(TF_WORKING_DIR) fmt -check
  displayName: 'Terraform Format Check'

# Step 5: Terraform Validate
- script: |
    terraform -chdir=$(TF_WORKING_DIR) validate
  displayName: 'Terraform Validate'

# Step 6: Terraform Plan
- script: |
    terraform -chdir=$(TF_WORKING_DIR) plan -out=tfplan
  displayName: 'Terraform Plan'

# Step 7 (Optional): Apply
# - script: |
#     terraform -chdir=$(TF_WORKING_DIR) apply -auto-approve tfplan
#   displayName: 'Terraform Apply'
